### ISSUE TITLE
Reorganise projects so source is separate from godot project

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/gdnative-demos#14]
Most of our sample projects have a structure where the godot project is in the root, we then have a src folder with sources.

The problem on Windows is that after compiling the sources we have a bunch of .obj files (compiled source) and Godot is attempting to import those as wavefront meshes.

A structure like:
```
sample
  + Source
    - SConstruct
    - sample.c
  + Demo
    + bin
      - libsample.gdnlib
      - sampleobj.gdns
      - libsample.dll
    - project.godot
    - main.tscn
```

Would probably be better

**Comment by karroffel** [comment]
alternatively a `.gdignore` file can be put in the source/build directory, then Godot won't attempt to import the obj files.

**Comment by aaronfranke** [comment]
Any update on this issue?

**Comment by aaronfranke** [comment]
Since the `SConstruct` has to interact with the project folder to save the compiled file, what about something like this?

```
sample
    SConstruct
    src/
        sample.c
    project/
        project.godot
        gdnative/
            libsample.gdnlib
            sampleobj.gdns
            libsample.dll
```

Also, would it be better if the files in the project were instead in `addons/sample/` or something? Maybe this works better for some projects than it does for others?

**Comment by aaronfranke** [comment]
Closing since this has been solved. All projects in this repo now have the C/C++ files separate from the project files.

**Comment by aaronfranke** [comment]
Since we have `.gdignore` in Godot to prevent Godot from trying to important `.obj` files or anything else in that folder, I'm wondering if this is necessary anymore, and if either way would work fine.
