### ISSUE TITLE
add windows example

### ISSUE THREAD

**Issue by Triangle345** [godotengine/gdnative-demos#18]
Linux and Osx examples exist but nothing for windows.

**Comment by haxpor** [comment]
I think it's merely about compilation flags to be added into `SConstrct` file. The demo would be working the same on Windows.

**Comment by Triangle345** [comment]
Correct it does work with scons but it is missing from the readme. However; both Linux and Osx there.. not a big deal, just for presentation purposes.

**Comment by aaronfranke** [comment]
The demos now work on Windows. Closing as fixed.
