### ISSUE TITLE
Move the WebRTC demos to this repository

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/gdnative-demos#33]
https://github.com/godotengine/godot-demo-projects/tree/master/networking

The WebRTC demos use GDNative, so they should be moved to this repository.

CC @Faless since you wrote these demos. Would you be able to handle this task?

**Comment by Faless** [comment]
Well, WebRTC uses GDNative only for native exports, it works without it on the web.
Additionally, it's not really a demo "on" GDNative. more a demo were you just need to drop in an additional GDNative file for it to work on some platforms.
I'm not sure it should be moved.

**Comment by aaronfranke** [comment]
@Faless I'll close this then, it's your call, and I see your point (and I see that the demo itself doesn't contain GDNative code directly, but just links to [here](https://github.com/godotengine/godot-demo-projects/tree/master/networking/webrtc_signaling) to download a plugin).

P.S. Are you planning to do a release of webrtc-native anytime soon? It seems that the repo has activity, but the last release was over a year ago, and it's marked as a "pre-release". Perhaps it's time for a stable release?

P.P.S. Could you add README files to the networking demos that are missing them?
