### ISSUE TITLE
Windows running cpp/simple project results in failure.

### ISSUE THREAD

**Issue by glipR** [godotengine/gdnative-demos#42]
After following the steps outlined in cpp/README.md, I tried to build the simple project for godot 3.2.3.

(So cd godot-cpp; scons platform=windows generate_bindings=yes; cd ..; scons platform=windows)

The first problem I ran into was the following:

scons: Building targets ...
link /nologo /WX /dll /out:bin\libsimple.dll /implib:bin\libsimple.lib /LIBPATH:godot-cpp\bin libgodot-cpp.linux.debug.64.lib src\entry.obj src\Simple.obj
LINK : fatal error LNK1181: cannot open input file 'libgodot-cpp.linux.debug.64.lib'
scons: *** [bin\libsimple.dll] Error 1181
scons: building terminated because of errors.

After changing libgodot-cpp.linux.debug.64 to libgodot-cpp.windows.debug.64 in the SConstruct scons did not fail, but when opening the project in godot I'm met with the following error.

ERROR:  does not have a library for the current platform.
   At: modules/gdnative/nativescript/nativescript.cpp:1483

**Comment by Calinou** [comment]
> After changing libgodot-cpp.linux.debug.64 to libgodot-cpp.windows.debug.64 in the SConstruct scons did not fail, but when opening the project in godot I'm met with the following error.
> 
> ERROR: does not have a library for the current platform.
At: modules/gdnative/nativescript/nativescript.cpp:1483

This is because `cpp/simple`'s .gdnlib only references a Linux library: https://github.com/godotengine/gdnative-demos/blob/master/cpp/simple/bin/simple.gdnlib

**Comment by glipR** [comment]
Thanks, fixed.

Worth noting that the editor itself crashed with that error because I originally had `godot-cpp` in the `simple` folder, but moving it a directory up seems to stop it from crashing completely. This difference isn't really noted in documentation either, and the defaults for the SCons file seem to indicate that it should be in the simple folder. Might have a PR later addressing both of these things, thanks again :)

**Comment by aaronfranke** [comment]
@glipR PRs to this repo would be much appreciated. If you can, take a look at how the C demos are structured (split Godot project, headers, and C source, and a nice SConstruct file). I've been wanting to improve the C++ demos but I haven't gotten around to it yet. There also might be problems with the C demos that I'm not aware of, so if you see something out of place, feel free to point it out or make a PR.
